
# Language/versions
language: node_js
matrix:
  include:
    - node_js: '12'
    - node_js: '14'

# Build only master (and pull-requests)
branches:
  only:
    - master

# Services setup
services:
  - mongodb

# Build script
before_script:
  - cp config/test.sample.json config/test.json
  - NODE_ENV=test node index.js &
  - sleep 5 # give server time to start
script: 'make ci'
